version: "3"

services:
  traefik:
    image: traefik:v2.9.4
    command: "--entrypoints.web.address=0.0.0.0:80
     --providers.docker 
     --providers.docker.exposedByDefault=false 
     --providers.docker.network=pycon-fastapi_traefik 
     '--providers.docker.constraints=Label(`pycon.traefik`,`true`)'"
    ports:
      - 8081:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traefik
  backend:
    environment:
      PROXY_ROOT_PATH: /api
      CHAT_BACKEND: memory
      AUTH_BACKEND: memory
    build:
      context: pycon-chat
    image: pycon_chat
    networks:
      - traefik
      - redis
    volumes:
      - ./pycon-chat/pycon_chat:/app/pycon_chat
    labels:
      - 'traefik.http.routers.pycon-chat-backend.rule=PathPrefix(`/api/`)'
      - 'traefik.http.middlewares.pycon-chat-backend-strip-prefix.stripprefix.prefixes=/api'
      - 'traefik.http.routers.pycon-chat-backend.middlewares=pycon-chat-backend-strip-prefix'
      - 'traefik.enable=true'
      - 'pycon.traefik=true'
  frontend:
    build:
      context: frontend
    image: pycon-chat-frontend
    networks:
      - traefik
    labels:
      - 'traefik.http.routers.pycon-chat-frontend.rule=PathPrefix(`/`)'
      - 'traefik.enable=true'
      - 'pycon.traefik=true'
  redis:
    image: redis:7.0.5
    networks:
      - redis

networks:
  traefik:
  redis: